version: '3'

services:
  skinnyhtml2pdf:
    image: oceanswave/skinnyhtml2pdf
    build:
      context: .
      dockerfile: BaristaLabs.SkinnyHtml2Pdf.Web/Dockerfile
    ports:
      - "80:8080"
    cap_add:
      - SYS_ADMIN
