version: '3'

services:
  skinny-html2pdf:
    image: oceanswave/skinny-html2pdf
    build:
      context: .
      dockerfile: BaristaLabs.SkinnyHtml2Pdf.Web/Dockerfile
    ports:
      - "80:8080"
    cap_add:
      - SYS_ADMIN
